### ISSUE TITLE
:bulb: Incorrect Use of MIT License

### ISSUE THREAD

**Issue by nullqwertyuiop** [Summid/FurryUniversityFramework#1]
### Description
I noticed that your Visual Novel game is using the MIT License, but this may not be the most appropriate license for your project. The MIT License grants broad permissions, including commercial use, which may not be suitable for your goals.

### Consequences
Using the `MIT License` may lead to unintended consequences, such as allowing others to use, modify, and distribute your work in ways that conflict with your intentions. For example, someone could take your work and use it for commercial purposes without your permission.

### Suggestion
I would like to suggest that you consider a more appropriate license, such as the `Creative Commons Attribution-NonCommercial-NoDerivatives License`. This license would prevent commercial use and modification of your work, while allowing non-commercial sharing.

Alternatively, if you need to prohibit sharing as well, you could consider the `Creative Commons Attribution-NonCommercial-NoDerivatives-NoSharing License`, which would limit the use of your work to personal use only.

### Discussion
I would be happy to discuss this further with you to help you choose the most appropriate license for your project. Please let me know if you have any questions or concerns.

Thank you for your attention to this matter.

**Comment by Summid** [comment]
谢谢你的提醒，该项目使用 MIT 协议是我的本意。~~应该没有其他人会使用这个破框架去开发游戏吧。~~

把核心部分公开出来的目的是为了和大伙儿学习交流，因此我持着开放包容的心态。并且该框架目前处于实验性质的状态，还未正式投入生产，后续也不会上传业务相关的代码和资源。

虚拟小说框架只是通用框架的一个子集，后续我可能会开启通用框架的项目，那时我会重新考虑使用何种协议的事情。

Thanks for the reminder, it was my intention to use the MIT license for this project.  ~~No one else will use this poor framework to develop games.~~

The purpose of disclosing the core part is to learn and communicate with everyone, so I hold an open and inclusive attitude. Moreover, the framework is currently in an experimental state and has not yet been officially put into production, and business-related codes and resources will not be uploaded in the future.

The virtual novel framework is only a subset of the general framework. I may start the general framework project later, and then I will reconsider which protocol to use.
